## Numpy array and basics
learn about numpy

import numpy as np

In [3]:
import numpy as np

creating array from list

In [4]:
array_1d=np.array([1,2,3,4,5])
print (array_1d)

array_2d=np.array([[1,2,3],[4,5,6]])
print (array_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [6]:
import time 
start = time.time()
py_list=[i*2 for i in range(1000)]
print ("\n List operation time :",time.time()-start)

start = time.time()
np_array=np.arange(1000)*2
print ("\n Numpy operation time:",time.time()-start)


 List operation time : 0.0032579898834228516

 Numpy operation time: 0.0005826950073242188


In [7]:
#creating array from scratch
zeros=np.zeros((3,4))
print ("zeros array:\n",zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#ones array
ones=np.ones((2,3))
print (ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
full =np.full((2,2),7)
print (full)

[[7 7]
 [7 7]]


In [10]:
random=np.random.random((2,3))
print (random)

[[0.25735529 0.67662044 0.0348434 ]
 [0.64788697 0.85852983 0.74725849]]


In [11]:
sequence = np.arange(0,10,2)

In [12]:
print (sequence)

[0 2 4 6 8]


#Vector,Matrix,Tensor

In [14]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6]])
tensor=np.array([[[1,2],[2,3],[4,5]],[[6,7],[8,9],[10,11]]])
print (tensor)

[[[ 1  2]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [16]:
##array properties
array=np.array([[1,2,3],[4,5,6]])
print (array.shape)
print(array.ndim)
print (array.size)
print(array.dtype)

(2, 3)
2
6
int64


In [21]:
#array reshapiung
arr=np.arange(12)
print (arr)

reshaped=arr.reshape((3,4))
print ("reshaped:",reshaped)

flattened=reshaped.flatten()
print ("flattened:",flattened)

#ravel (returns views,returns a copy)
raveled=reshaped.ravel()
print ("raveled:",raveled)

#transpose 
transpose =reshaped.T
print ("Transposed:",transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
