In [ ]:
import numpy as np

In [4]:
#Indexing and slicing
import numpy as np

arr = np.array([1,2,3,4,5])
print("basic slicing:", arr[2:])
print ("with step:",arr[1:3:2])
print ("Negative Indexing:",arr[-3])

basic slicing: [3 4 5]
with step: [2]
Negative Indexing: 3


In [ ]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print ("specefic element:",arr_2d[1,2])
print ("entire row:",arr_2d[1])
print ("entire column :",arr_2d[:,1])

specefic element: 6
entire row: [4 5 6]
entire row : [2 5 8]


In [6]:
#sorting

unsorted =np.array([3,1,2,8,9])
print ("sorted array :",np.sort(unsorted))

sorted array : [1 2 3 8 9]


In [8]:
arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print ("sorted 2D array by column:",np.sort(arr_2d_unsorted,axis=0))
print ("sorted 2D array by column:",np.sort(arr_2d_unsorted,axis=1))

sorted 2D array by column: [[1 1]
 [2 2]
 [3 3]]
sorted 2D array by column: [[1 3]
 [1 2]
 [2 3]]


In [9]:
#filter 

numbers =np.array([1,2,3,4,5,6,7,8,9,10])
even = numbers[numbers%2==0]
print ("even numbers:",even)

even numbers: [ 2  4  6  8 10]


In [11]:
##filter with mask

mask = numbers>5
print ("Numbers greater than 5:",numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


In [12]:
## Fancy indexing 
indices = [0,2,4]


In [13]:
print (numbers[indices])
where_res=np.where(numbers>5)
print ("NP where:",numbers[where_res])

[1 3 5]
NP where: [ 6  7  8  9 10]


In [16]:
condition_array=np.where(numbers>5,"True","False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


In [ ]:
### adding and removing data


arr=np.array([1,2,3])
arr2=np.array([4,5,6])
# comb=arr+arr2  Not work
comb=np.concatenate((arr,arr2))
print(comb)

[1 2 3 4 5 6]


In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print ("compatibility shapes:",a.shape==b.shape)

compatibility shapes: True


In [22]:
original=np.array([[1,2,3],[4,5,6]])
new_row=np.array([[8,9,10]])
with_new_row=np.vstack((original,new_row))
print (with_new_row)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [23]:
new_col=np.array([[7,8],[9,10]])

with_new_col=np.hstack((original,new_col))
print (with_new_col)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [25]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print ("array after deletion",deleted)


array after deletion [1 2 4 5]
